'use strict';
// Production functions and Canvas command validation in Node, not a browser/GPU test.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const html=fs.readFileSync(path.join(__dirname,'../dist/index.html'),'utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
let checks=0,canvasCommands=0;
function check(ok,message){assert(ok,message);checks++}
function equal(a,b,message){assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)),message);checks++}
function context(){
 const nodes=new Map(),memory=new Map(),query={matches:false,addEventListener(){}};
 const contexts=[];
 function makeCanvas(){const c={};for(const name of ['clearRect','fillRect','translate','rotate','ellipse','arc','moveTo','bezierCurveTo','rect'])c[name]=(...args)=>{check(args.every(Number.isFinite),'finite Canvas '+name);if(name==='ellipse'||name==='arc')check(args[2]>=0,'positive radius');canvasCommands++};for(const name of ['save','restore','beginPath','fill','stroke','clip'])c[name]=()=>{canvasCommands++};c.drawImage=(image,...args)=>{check(args.every(Number.isFinite),'finite image coordinates');canvasCommands++};c.createLinearGradient=()=>({addColorStop(){}});c.createImageData=(w,h)=>({data:new Uint8ClampedArray(w*h*4)});c.putImageData=()=>{};contexts.push(c);return c}
 function element(id=''){if(nodes.has(id))return nodes.get(id);let child;const n={id,tagName:'DIV',hidden:false,width:0,height:0,complete:true,naturalWidth:1254,children:[],value:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},addEventListener(){},focus(){doc.activeElement=n},querySelector(){return child||(child=element(id+'-small'))},querySelectorAll(){return []},replaceChildren(){this.children=[]},append(v){this.children.push(v)},getBoundingClientRect(){return {width:340,height:180}},getContext(){return this.ctx||(this.ctx=makeCanvas())}};nodes.set(id,n);return n}
 const ingredients=['water','rice','koji','yeast'].map(k=>{const n=element(k+'-button');n.dataset.ingredient=k;n.tagName='BUTTON';return n});
 const doc={hidden:false,body:element('body'),activeElement:null,getElementById:element,createElement:()=>element('created-'+nodes.size),querySelector:selector=>ingredients.find(x=>selector.includes('"'+x.dataset.ingredient+'"')),querySelectorAll:selector=>selector.includes('data-ingredient')?ingredients:[],addEventListener(){}};
 doc.body.children=[];
 const c={Math,console,Map,Set,Float32Array,Uint16Array,Uint8ClampedArray,document:doc,window:{addEventListener(){}},matchMedia:()=>query,localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},performance:{now:()=>0},setTimeout:()=>0,clearTimeout(){},requestAnimationFrame:()=>0,innerWidth:390,innerHeight:844,devicePixelRatio:3};vm.createContext(c);vm.runInContext(script.slice(0,script.indexOf('\ninitGL();buildWorld();')),c);
 const run=code=>vm.runInContext(code,c);run("notify=()=>{};soundCue=()=>{};kura.scene='micro';initIngredientEffects();$('resultOverlay').hidden=true;panel='setupPanel';");return {c,run,nodes,memory,query,contexts};
}
const t=context();check(t.run('settings.animations')===true,'animations default ON');check(t.run('animationsEnabled()')===true,'default effective motion enabled');
t.run("addIngredient('water');addIngredient('rice');addIngredient('koji');addIngredient('yeast');");equal(t.run('[...game.ingredients]'),['water','rice','koji','yeast'],'all ingredients commit immediately before effects finish');equal(t.run('ingredientFX.queue'),['rice','koji','yeast'],'four bounded events queue in order');
for(let i=0;i<100;i++)t.run("addIngredient('koji');addIngredient('water')");check(t.run('ingredientFX.queue.length')===3,'repeated clicks cannot grow queue');check(t.run('game.ingredients.size')===4,'replay never duplicates ingredient');
let order=['water'],last='water';const gameTime=t.run('game.time');for(let i=0;i<280;i++){t.run('tickIngredientEffects(.05,'+i*50+')');const k=t.run('ingredientFX.kind');if(k!==last){order.push(k);last=k}}
equal(order,['water','rice','koji','yeast'],'all four effects execute with setup panel open');equal(t.run('game.time'),gameTime,'effect clock does not advance gameplay in a panel');check(!t.run('ingredientFX.active'),'all effects terminate');check(t.nodes.get('ingredientWorldFX').hidden,'world layer hides when idle');check(t.nodes.get('ingredientCanvas').width<=640,'stage pixel width bounded');check(t.nodes.get('ingredientWorldFX').width<=960&&t.nodes.get('ingredientWorldFX').height<=600,'world overlay resolution bounded');
t.run("queueIngredientEffect('water');tickIngredientEffects(.05,20000);paused=true;");const frozen=t.run('ingredientFX.time');for(let i=0;i<30;i++)t.run('tickIngredientEffects(.05,21000)');equal(t.run('ingredientFX.time'),frozen,'explicit pause freezes effects');t.run('paused=false;hiddenPause=true;tickIngredientEffects(.05,22000)');equal(t.run('ingredientFX.time'),frozen,'hidden tab freezes effects');t.run('hiddenPause=false;');
t.run("queueIngredientEffect('rice');queueIngredientEffect('koji');settings.animations=false;applyMotionSettings()");check(!t.run('ingredientFX.active'),'OFF immediately stops live effect');equal(t.run('ingredientFX.queue.length'),0,'OFF clears pending effects');equal(t.run('ingredientFX.kind'),'koji','OFF presents latest requested ingredient');
t.run("addIngredient('yeast');tickIngredientEffects(.05,23000)");check(!t.run('ingredientFX.active'),'OFF replay stays static');check(t.run('game.ingredients.size')===4,'OFF preserves ingredients');check(!t.run('animationsEnabled()'),'OFF disables ambient motion');t.run('save()');const stored=JSON.parse(t.memory.get('shubo.v2'));equal(stored.settings.animations,false,'OFF persists');check(!('effects' in stored.run),'ephemeral effects not saved');
t.run('settings.animations=true;settings.reduced=false;');t.query.matches=true;t.run('applyMotionSettings()');check(!t.run('animationsEnabled()'),'OS reduced motion overrides prior false preference');t.query.matches=false;t.run('settings.reduced=true;applyMotionSettings()');check(!t.run('animationsEnabled()'),'in-game reduced motion also respected');t.run('settings.reduced=false;applyMotionSettings()');check(t.run('animationsEnabled()'),'ON resumes ambient motion');
t.run("queueIngredientEffect('rice');getMistTexture('rice');this.mistBefore=mistTexture;getMistTexture('koji');");check(t.run('mistBefore===mistTexture'),'steam and spores reuse a single mist canvas');
t.run("queueIngredientEffect('yeast');panelClose()");check(!t.run('ingredientFX.active')&&!t.run('ingredientFX.queue.length'),'closing panel cancels pending effects');
t.run("panel='setupPanel';queueIngredientEffect('yeast');startBatch()");check(!t.run('ingredientFX.active'),'start cancels effects');check(t.run('game.active'),'start remains available independent of animation');
// Animate-free gameplay: player input and simulation continue; no idle camera drift.
t.run("settings.animations=false;applyMotionSettings();panel=null;mode='yeast';paused=false;game.active=true;this.sceneDraws=0;fallback={};drawFallback=()=>{sceneDraws++};this.simBefore=simTime;this.playBefore=game.time;this.posBefore=[...player.pos];input.keys.add('w');");for(let i=1;i<=60;i++)t.run('frame('+i*16.67+')');check(t.run('game.time>playBefore'),'OFF preserves game clock');check(t.run('player.pos[2]<posBefore[2]'),'OFF preserves movement');equal(t.run('simTime'),t.run('simBefore'),'OFF freezes automatic scene animation');t.run('input.keys.clear();sceneDraws=0');for(let i=61;i<=120;i++)t.run('frame('+i*16.67+')');check(t.run('sceneDraws')<=8,'static OFF scene redraw is bounded');
check(t.run('cleanSettings({}).animations'),'old saves default to ON');check(!t.run('cleanSettings({animations:false}).animations'),'explicit OFF survives settings migration');
t.run('this.drawsBefore=sceneDraws;camera.distance*=.9;frame(2001)');equal(t.run('sceneDraws'),t.run('drawsBefore+1'),'OFF camera zoom repaints without the idle delay');
// Bounded render commands in portrait and landscape throughout each effect.
for(const [width,height] of [[320,568],[390,844],[844,390],[1440,900]])for(const kind of ['water','rice','koji','yeast']){t.c.innerWidth=width;t.c.innerHeight=height;t.run("settings.animations=true;settings.reduced=false;panel='setupPanel';clearIngredientEffects();beginIngredientEffect('"+kind+"');");for(let i=0;i<=32;i++)t.run('ingredientFX.time='+i/10+';paintIngredientStage();paintIngredientWorld();')}
const asset=html.match(/id="ingredientAtlas"[^>]+src="data:image\/jpeg;base64,([^"]+)"/);check(!!asset,'new art embedded in HTML');const jpeg=Buffer.from(asset[1],'base64');check(jpeg[0]===255&&jpeg[1]===216&&jpeg.at(-2)===255&&jpeg.at(-1)===217,'complete JPEG payload');check(html.length<2000000,'single-file byte budget');
console.log(JSON.stringify({status:'PASS',checks,canvasCommands,htmlSha256:crypto.createHash('sha256').update(html).digest('hex'),embeddedImageBytes:jpeg.length,maxQueuedEffects:4,maxMistLayers:1,effectDurationSeconds:3.2,scope:'Node VM event clocks, state, Canvas command bounds and embedded payload. No browser, GPU, screenshots or physical device testing.'},null,2));
