'use strict';
const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const engine=process.argv[2]||'chromium';const browser=await ({chromium,webkit}[engine]).launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});let checks=0;const errors=[];const out='/private/tmp';
const context=await browser.newContext({viewport:{width:402,height:874},hasTouch:true,deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const check=(condition,label)=>{assert(condition,label);checks++};const debug=()=>page.evaluate(()=>window.shuboDebug);const waitScene=scene=>page.waitForFunction(s=>window.shuboDebug.presentation.scene===s&&window.shuboDebug.presentation.transition===null,scene);
await page.goto('http://127.0.0.1:8768/');await page.waitForFunction(()=>window.shuboDebug?.presentation.paperReady&&window.shuboDebug?.presentation.brewerReady);check((await debug()).presentation.scene==='kura','opens brewery');check((await debug()).settings.animations,'motion default on');await page.locator('#enterVat').click();await page.waitForFunction(()=>window.shuboDebug.presentation.phase==='peek'&&!window.shuboDebug.presentation.transition);await page.locator('#enterVat').click();await waitScene('micro');check((await debug()).settings.style==='character','vat enters LIFE');
await page.locator('#primaryAction').click();for(const kind of ['water','rice','koji','yeast'])await page.locator('[data-ingredient="'+kind+'"]').click();await page.locator('#startBatch').click();check((await debug()).game.active,'ingredients start run');await page.locator('#pause').click();const before=await debug();await page.locator('#layerKura').click();await page.waitForTimeout(350);check((await debug()).game.time===before.game.time,'KURA freezes run');await page.locator('#layerLife').click();await waitScene('micro');let after=await debug();for(const key of ['time','sugar','vitality','ferment','risk','energy','buds','batch'])check(after.game[key]===before.game[key],'LIFE retains '+key);check(after.presentation.paperCount>0,'paper yeast and koji present');await page.waitForTimeout(200);await page.screenshot({path:out+'/shubo-life-mobile.png'});
await page.locator('#layerReal').click();after=await debug();check(after.settings.style==='realistic','REAL switch');check(after.presentation.paperCount===0,'REAL has no paper actors');check(after.game.time===before.game.time,'style switch does not advance run');await page.waitForTimeout(200);await page.screenshot({path:out+'/shubo-real-mobile.png'});
await page.locator('[data-mode="cell"]').click();check((await debug()).mode==='cell','cell mode reachable');await page.locator('#layerLife').click();check((await debug()).mode==='world','LIFE exits scientific cutaway');await page.locator('[data-mode="yeast"]').click();await page.waitForTimeout(200);await page.screenshot({path:out+'/shubo-paper-player.png'});check((await debug()).presentation.paperCount>=5,'player and environment paper');
await page.locator('#settingsButton').click();check(await page.locator('#settingsPanel').isVisible(),'settings opens');await page.locator('#panelBackdrop').click({position:{x:3,y:200}});check(!await page.locator('#settingsPanel').isVisible(),'outside click dismisses panel');
await page.locator('#layerKura').click();const saveBefore=await page.evaluate(()=>JSON.parse(localStorage.getItem('shubo.v2')));await page.reload();await page.waitForFunction(()=>window.shuboDebug?.presentation.paperReady);check((await debug()).presentation.scene==='kura','reload starts exterior');check((await debug()).game.time===saveBefore.run.time,'save time restored');check((await debug()).mode===saveBefore.run.mode,'saved micro mode restored');check((await debug()).paused,'active save waits for resume');
await page.locator('#layerMotion').click();await page.locator('#layerLife').click();await waitScene('micro');await page.locator('#pause').click();await page.keyboard.down('w');await page.waitForTimeout(400);await page.keyboard.up('w');const moved=await debug();check(moved.player.pos[2]<saveBefore.run.pos[2],'motion OFF still moves player');await page.locator('#layerKura').click();const frozen=(await debug()).game.time;await page.waitForTimeout(350);check((await debug()).game.time===frozen,'unpaused game still sleeps in KURA');
// Mature saved-world fixture checks high population and all visual modes without changing production hooks.
await page.addInitScript(()=>{const s=JSON.parse(localStorage.getItem('shubo.v2'));Object.assign(s.run,{active:false,finished:true,explore:true,ferment:100,vitality:87,risk:10,buds:3,energy:4,time:380,mode:'world',paused:true});s.settings.style='character';s.settings.animations=false;localStorage.setItem('shubo.v2',JSON.stringify(s));});await page.reload();await page.waitForFunction(()=>window.shuboDebug?.presentation.paperReady);await page.locator('#layerLife').click();await waitScene('micro');await page.waitForTimeout(200);await page.screenshot({path:out+'/shubo-life-mature.png'});check((await debug()).presentation.paperCount<=64,'sprite population bounded');await page.setViewportSize({width:1200,height:900});await page.waitForTimeout(200);await page.screenshot({path:out+'/shubo-life-desktop.png'});
for(const [width,height] of [[320,568],[402,874],[874,402],[1200,900]]){await page.setViewportSize({width,height});await page.waitForTimeout(250);check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no horizontal overflow '+width);await page.locator('#layerKura').click();check(await page.locator('#enterVat').isVisible(),'vat CTA reachable '+width);await page.locator('#layerLife').click();await waitScene('micro');}
// No WebGL: the same entrance and gameplay remain available through 2D rendering.
const fallback=await browser.newContext({viewport:{width:402,height:874},reducedMotion:'reduce'});await fallback.addInitScript(()=>{const old=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl'||type==='webgl2'?null:old.call(this,type,...args)};});const fp=await fallback.newPage();fp.on('pageerror',e=>errors.push('fallback: '+e.message));await fp.goto('http://127.0.0.1:8768/');await fp.waitForFunction(()=>window.shuboDebug);check((await fp.evaluate(()=>window.shuboDebug.render.renderer))==='2d','2D fallback');await fp.locator('#enterVat').click();await fp.locator('#enterVat').click();await fp.waitForFunction(()=>window.shuboDebug.presentation.scene==='micro');check(!await fp.evaluate(()=>window.shuboDebug.effects.animations),'reduced motion suppresses automatic animation');await fp.screenshot({path:out+'/shubo-fallback.png'});await fp.locator('#layerKura').click();await fp.screenshot({path:out+'/shubo-kura-fallback.png'});check(errors.length===0,'no browser errors: '+errors.join('\n'));
console.log(JSON.stringify({status:'PASS',engine,checks,errors,scope:'Local browser GPU + 2D fallback, 402x874 touch viewport and responsive widths; no physical iPhone test.'},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
